### ISSUE TITLE
dashboards not being assigned to folders 

### ISSUE THREAD

**Issue by ofirshtrull** [ezienecker/grafana-sidecar-folder-sample#1]
hi,
thanks for the guide,
I still have a problem maybe you will know how to fix

I add the config like you wrote
```yaml
          dashboardProviders:
            dashboardproviders.yaml:
              apiVersion: 1
              providers:
              - name: "Inventory Summary"
                orgId: 1
                folder: "edge"
                type: file
                disableDeletion: false
                editable: false
                options:
                  path: /tmp/dashboards/inventory
```

and add the anotatin to the cm
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-dashboards
  labels:
    grafana_dashboard: "1"
  annotations:
    k8s-sidecar-target-directory: "/tmp/dashboards/inventory"
data:
{{ (.Files.Glob "custom-dashboards/inventory/*.json" ).AsConfig | indent 2 }}

```

and the logs seem right 
```bash
Working on configmap staging/inventory-dashboards
Found a folder override annotation, placing the inventory-dashboards in: /tmp/dashboards/inventory
File in configmap Inventory_Summary.json ADDED
```

but when I go to the UI I see only empty folders (except the general)

what can it be that I am missing?

**Comment by ofirshtrull** [comment]
never mind turns out i needed also 
```yaml
          sidecar:
            dashboards:
              provider:
                foldersFromFilesStructure: true
```
to make it work
